import { Department, Designation, EmployeeType, EquipmentStatus, ProductCategory, ProductType, ProjectStatus, ProjectType } from "@prisma/client";

export type TProjectDetails = {
  id: string,
  projectName: string,
  department: Department,
  clientId: string,
  createdBy: string,
  projectManagerId: string,
  startDate: string,
  estimatedEndDate: string,
  projectType: ProjectType,
  productType: ProductType,
  status: ProjectStatus,
  street: string,
  city: string,
  state: string,
  zip: number,
  createdAt: string,
  updatedAt: string,
  projectManager: {
    id: string,
    mobile: string,
    employeeType: EmployeeType,
    department: Department,
    designation: Designation,
    officeLocation: string,
    user: {
      firstName: string,
      lastName: string,
      email: string,
      profileImage: string | null,
    },
  },
  client: {
    id: string,
    mobile: string,
    user: {
      firstName: string,
      lastName: string,
      email: string,
      profileImage: string | null,
    },
  },
  engineers: {
    engineers: {
      id: string,
      mobile: string,
      employeeType: EmployeeType,
      department: Department,
      designation: Designation,
      officeLocation: string,
      user: {
        firstName: string,
        lastName: string,
        email: string,
        profileImage: string | null,
      },
    },
  }[],
  products: {
    products: {
      id: string,
      equipmentId: string,
      equipmentName: string,
      equipmentImage: string[],
      registrationNumber: string,
      category: ProductCategory,
      status: EquipmentStatus,
      createdAdminId: string,
      ownerName: string,
      ownerAddress: string,
      ownerNumber: string,
      charteredBy: string,
      charteredPersonPhone: string,
      charteredPersonAddress: string,
      brandName: string,
      model: string,
      dimensions: string,
      manufacturingYear: string,
      createdAt: string,
      updatedAt: string,
    },
  }[],
};
